#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
FIFO="/tmp/linux_os_management_fifo"
rm -f "$FIFO"

echo ""
echo "=================================================="
echo "          FIFO TWO-TERMINAL DEMO"
echo "=================================================="
echo ""
echo "Open TWO terminals in this same project folder."
echo ""
echo "TERMINAL 1 (Reader):"
echo "  ./fifo_demo reader"
echo ""
echo "TERMINAL 2 (Writer):"
echo "  ./fifo_demo writer"
echo ""
echo "In Terminal 2, type your message."
echo "It will appear in Terminal 1 as the received message."
echo ""
echo "=================================================="
